
package com.star.sms.haiwai.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IHaiWaiElectronicPaymentService", targetNamespace = "http://service.haiwai.sms.star.com", wsdlLocation = "file:startimes/electronicPaymentService_1.wsdl")
public class IHaiWaiElectronicPaymentService
    extends Service 
{

    private final static URL IHAIWAIELECTRONICPAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException IHAIWAIELECTRONICPAYMENTSERVICE_EXCEPTION;
    private final static QName IHAIWAIELECTRONICPAYMENTSERVICE_QNAME = new QName("http://service.haiwai.sms.star.com", "IHaiWaiElectronicPaymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("file:/C:/Users/NJINU/Desktop/star%20times/electronicPaymentService_1.wsdl");
            url = new URL("file:startimes/electronicPaymentService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IHAIWAIELECTRONICPAYMENTSERVICE_WSDL_LOCATION = url;
        IHAIWAIELECTRONICPAYMENTSERVICE_EXCEPTION = e;
    }

    public IHaiWaiElectronicPaymentService() {
        super(__getWsdlLocation(), IHAIWAIELECTRONICPAYMENTSERVICE_QNAME);
    }

    public IHaiWaiElectronicPaymentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IHAIWAIELECTRONICPAYMENTSERVICE_QNAME, features);
    }

    public IHaiWaiElectronicPaymentService(URL wsdlLocation) {
        super(wsdlLocation, IHAIWAIELECTRONICPAYMENTSERVICE_QNAME);
    }

    public IHaiWaiElectronicPaymentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IHAIWAIELECTRONICPAYMENTSERVICE_QNAME, features);
    }

    public IHaiWaiElectronicPaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHaiWaiElectronicPaymentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHaiWaiElectronicPaymentServicePortType
     */
    @WebEndpoint(name = "IHaiWaiElectronicPaymentServiceHttpPort")
    public IHaiWaiElectronicPaymentServicePortType getIHaiWaiElectronicPaymentServiceHttpPort() {
        return super.getPort(new QName("http://service.haiwai.sms.star.com", "IHaiWaiElectronicPaymentServiceHttpPort"), IHaiWaiElectronicPaymentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHaiWaiElectronicPaymentServicePortType
     */
    @WebEndpoint(name = "IHaiWaiElectronicPaymentServiceHttpPort")
    public IHaiWaiElectronicPaymentServicePortType getIHaiWaiElectronicPaymentServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.haiwai.sms.star.com", "IHaiWaiElectronicPaymentServiceHttpPort"), IHaiWaiElectronicPaymentServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IHAIWAIELECTRONICPAYMENTSERVICE_EXCEPTION!= null) {
            throw IHAIWAIELECTRONICPAYMENTSERVICE_EXCEPTION;
        }
        return IHAIWAIELECTRONICPAYMENTSERVICE_WSDL_LOCATION;
    }

}
