package com.star.sms.haiwai.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.star.sms.model.haiwai.CustomerPayDto2;
import com.star.sms.model.haiwai.CustomerPayResult2;
import com.star.sms.model.haiwai.SubscriberQueryResult;
import com.star.sms.model.haiwai.ThirdPartnerRes;
import com.star.sms.model.haiwai.condition.RechargeAndChangeProductCondition;
import com.star.sms.model.haiwai.condition.SubscriberQueryCondition;
import com.star.sms.service.model.BalanceInfo;
import com.star.sms.service.model.CustomerPayResult;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "IHaiWaiElectronicPaymentServicePortType", targetNamespace = "http://service.haiwai.sms.star.com")
@XmlSeeAlso({
    com.star.sms.haiwai.service.ObjectFactory.class,
    com.star.sms.model.haiwai.ObjectFactory.class,
    com.star.sms.model.haiwai.condition.ObjectFactory.class,
    com.star.sms.service.model.ObjectFactory.class
})
public interface IHaiWaiElectronicPaymentServicePortType {

    /**
     *
     * @param in0
     * @return returns com.star.sms.model.haiwai.SubscriberQueryResult
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.haiwai.sms.star.com")
    @RequestWrapper(localName = "querySubscriberInfo", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.QuerySubscriberInfo")
    @ResponseWrapper(localName = "querySubscriberInfoResponse", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.QuerySubscriberInfoResponse")
    public SubscriberQueryResult querySubscriberInfo(
            @WebParam(name = "in0", targetNamespace = "http://service.haiwai.sms.star.com") SubscriberQueryCondition in0);

    /**
     *
     * @param deviceType
     * @param smartCardCode
     * @param payerPwd
     * @param transactionNo
     * @param payerID
     * @param customerCode
     * @param customerPwd
     * @return returns com.star.sms.service.model.BalanceInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.haiwai.sms.star.com")
    @RequestWrapper(localName = "queryBalance", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.QueryBalance")
    @ResponseWrapper(localName = "queryBalanceResponse", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.QueryBalanceResponse")
    public BalanceInfo queryBalance(
            @WebParam(name = "transactionNo", targetNamespace = "http://service.haiwai.sms.star.com") String transactionNo,
            @WebParam(name = "payerID", targetNamespace = "http://service.haiwai.sms.star.com") String payerID,
            @WebParam(name = "payerPwd", targetNamespace = "http://service.haiwai.sms.star.com") String payerPwd,
            @WebParam(name = "customerCode", targetNamespace = "http://service.haiwai.sms.star.com") String customerCode,
            @WebParam(name = "smartCardCode", targetNamespace = "http://service.haiwai.sms.star.com") String smartCardCode,
            @WebParam(name = "customerPwd", targetNamespace = "http://service.haiwai.sms.star.com") String customerPwd,
            @WebParam(name = "deviceType", targetNamespace = "http://service.haiwai.sms.star.com") String deviceType);

    /**
     *
     * @param in0
     * @return returns com.star.sms.model.haiwai.CustomerPayResult2
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.haiwai.sms.star.com")
    @RequestWrapper(localName = "customerPay2", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.CustomerPay2")
    @ResponseWrapper(localName = "customerPay2Response", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.CustomerPay2Response")
    public CustomerPayResult2 customerPay2(
            @WebParam(name = "in0", targetNamespace = "http://service.haiwai.sms.star.com") CustomerPayDto2 in0);

    /**
     *
     * @param deviceType
     * @param smartCardCode
     * @param transferTime
     * @param payerPwd
     * @param fee
     * @param transactionNo
     * @param payerID
     * @param customerCode
     * @param receiptCode
     * @param customerTel
     * @param customerName
     * @return returns com.star.sms.service.model.CustomerPayResult
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.haiwai.sms.star.com")
    @RequestWrapper(localName = "customerPay", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.CustomerPay")
    @ResponseWrapper(localName = "customerPayResponse", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.CustomerPayResponse")
    public CustomerPayResult customerPay(
            @WebParam(name = "transactionNo", targetNamespace = "http://service.haiwai.sms.star.com") String transactionNo,
            @WebParam(name = "payerID", targetNamespace = "http://service.haiwai.sms.star.com") String payerID,
            @WebParam(name = "payerPwd", targetNamespace = "http://service.haiwai.sms.star.com") String payerPwd,
            @WebParam(name = "customerCode", targetNamespace = "http://service.haiwai.sms.star.com") String customerCode,
            @WebParam(name = "customerName", targetNamespace = "http://service.haiwai.sms.star.com") String customerName,
            @WebParam(name = "customerTel", targetNamespace = "http://service.haiwai.sms.star.com") String customerTel,
            @WebParam(name = "smartCardCode", targetNamespace = "http://service.haiwai.sms.star.com") String smartCardCode,
            @WebParam(name = "fee", targetNamespace = "http://service.haiwai.sms.star.com") Double fee,
            @WebParam(name = "receiptCode", targetNamespace = "http://service.haiwai.sms.star.com") String receiptCode,
            @WebParam(name = "deviceType", targetNamespace = "http://service.haiwai.sms.star.com") String deviceType,
            @WebParam(name = "transferTime", targetNamespace = "http://service.haiwai.sms.star.com") String transferTime);

    /**
     *
     * @param in0
     * @return returns com.star.sms.model.haiwai.ThirdPartnerRes
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.haiwai.sms.star.com")
    @RequestWrapper(localName = "rechargeAndChangeProduct", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.RechargeAndChangeProduct")
    @ResponseWrapper(localName = "rechargeAndChangeProductResponse", targetNamespace = "http://service.haiwai.sms.star.com", className = "com.star.sms.haiwai.service.RechargeAndChangeProductResponse")
    public ThirdPartnerRes rechargeAndChangeProduct(
            @WebParam(name = "in0", targetNamespace = "http://service.haiwai.sms.star.com") RechargeAndChangeProductCondition in0);

}
